function [Bx, By, Bz] = Bsph2Bxyz(Br, Bth, Bphi, theta, phi)
% Convert vector components aligned to spherical coordinates
% into vector components aligned to cartesian axes.
% Source: Arfken, Weber, Harris, Mathematical Methods for Physicists,
% 7th ed, pg. 199 for the unit vectors.
    Bx =  sin(theta) .* cos(phi) .* Br ...
        + cos(theta) .* cos(phi) .* Bth ...
        - sin(phi) .* Bphi;
    By =  sin(theta) .* sin(phi) .* Br ...
        + cos(theta) .* sin(phi) .* Bth ...
        + cos(phi) .* Bphi;
    Bz =  cos(theta) .* Br ...
        - sin(theta) .* Bth;
end