function [Br, Bth, Bphi] = Bxyz2Bsph(Bx, By, Bz, theta, phi)
% Convert vector components aligned to cartesian axes
% into vector components aligned to spherical coordinates.
% Source: Arfken, Weber, Harris, Mathematical Methods for Physicists,
% 7th ed, pg. 199 for the unit vectors.
    Br   =  sin(theta) .* cos(phi) .* Bx ...
          + sin(theta) .* sin(phi) .* By ...
          + cos(theta) .* Bz;
    Bth  =  cos(theta) .* cos(phi) .* Bx ...
          + cos(theta) .* sin(phi) .* By ...
          - sin(theta) .* Bz;
    Bphi = -sin(phi) .* Bx ...
          + cos(phi) .* By;
end