function f = GetExcitations(moonName, etMid_day)
% Retrieve a list of excitation frequencies to invert.
%
% Returned excitation frequencies consist of combinations of precise orbital periods, including
% those adjusted for nutation and precession. For most bodies, one or more empirically determined
% oscillation periods are also included, such as those corresponding to the true anomaly period.
%
% Parameters
% ----------
% moonName : char, 1xC
%   Name of moon for which to return excitation frequencies.
% etMid_day : double, default=0
%   Ephemeris time (ET) near the center of time series to be evaluated in days. Default is J2000.
%
% Returns
% -------
% f : double, 1xP'
%   Frequencies of excitations in Hz.

% Part of the PlanetMag framework for evaluation and study of planetary magnetic fields.
% Created by Corey J. Cochrane and Marshall J. Styczinski
% Maintained by Marshall J. Styczinski
% Contact: corey.j.cochrane@jpl.nasa.gov
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

    if ~exist('etMid_day', 'var'); etMid_day = 0; end

    fEyr = 1 / 365.256 / 86400; % https://nssdc.gsfc.nasa.gov/planetary/factsheet/earthfact.html
    fJyr = 1 / 4332.589 / 86400; % https://nssdc.gsfc.nasa.gov/planetary/factsheet/jupiterfact.html
    fSyr = 1 / 10759.22 / 86400; % https://nssdc.gsfc.nasa.gov/planetary/factsheet/saturnfact.html
    fUyr = 1 / 30685.4 / 86400; % https://nssdc.gsfc.nasa.gov/planetary/factsheet/uranusfact.html
    fNyr = 1 / 60189 / 86400; % https://nssdc.gsfc.nasa.gov/planetary/factsheet/neptunefact.html
    % Fetch remaining quantities from PCK file
    [~, ~, ~, ~, omegaParent_radps, omegaMoon_radps, ~, ~, nutPrecParent, nutPrecMoon] ...
        = GetBodyParams(moonName);
    fPar = abs(omegaParent_radps / 2/pi);
    fOrb = abs(omegaMoon_radps / 2/pi);
    Pnut0 = nutPrecParent(1:2:end);
    Pnut1 = nutPrecParent(2:2:end) / 36525;
    fOrbAdj = abs(omegaMoon_radps / 2/pi + sum(nutPrecMoon .* Pnut1 .* cosd(Pnut0 ...
        + Pnut1*etMid_day)) / 360 / 86400);
    fSyn = fPar - fOrb;
    fSynAdj = fPar - fOrbAdj;
    
    switch moonName

        %% Earth moon
        case 'Moon'

            f = [fSyn, fOrb];

            f = [f, 2*fSyn];

        %% Jupiter moons 
        case 'Io'
            fIoTA = 1 / 3600 / 42.315044531808887029; % true anomaly period
            fOrbBeat = 1 / 3600 / 42.289036514276894252;
            fOrbMid1 = 1 / 3600 / 42.431381950208163;
            fOrbMid2 = 1 / 3600 / 42.305626942856122;

            f = [fSyn, fOrb, fIoTA, fOrbMid1, fOrbMid2];

            f = [f, 2*fSyn, ...
                    3*fSyn, ...
                    4*fSyn, ...
                    5*fSyn, ...
                    6*fSyn, ...
                    fSyn - fIoTA, ... % 1st harmonic beats
                    fSyn - fOrb, ...
                    fSyn + fOrb, ...
                    fSyn + fIoTA, ...
                    2*fSyn - fIoTA, ... % 2nd harmonic beats
                    2*fSyn + fIoTA, ...
                    3*fSyn - fIoTA, ... % 3rd harmonic beats
                    3*fSyn + fIoTA, ...
                    fSynAdj - fIoTA, ... % 1st harmonic beats
                    fSynAdj - fOrb, ... % 1st harmonic beats
                    fSynAdj + fIoTA, ...
                    2*fSynAdj - fIoTA, ... % 2nd harmonic beats
                    2*fSynAdj + fIoTA, ...
                    3*fSynAdj - fIoTA, ... % 3rd harmonic beats
                    3*fSynAdj + fIoTA, ...
                    fOrbBeat, ... % ~ 2nd harmonic beat between orbital and TA periods
                    fSynAdj - fOrbMid2, ...  % Beat between strong(est) oscillations
                    fPar - fJyr, ... % Solar oscillation periods due to 
                    fPar - 2*fJyr, ... % magnetopause current fields
                    fOrbAdj - fJyr, ...
                    fOrbAdj - 2*fJyr];

        case 'Europa'
            fTA = 1 / 84.62776 / 3600;
            fNearBeats = 1 / 3600 ./ [9.916007150192408304, 9.918866231039942249, ...
                9.924589341739000758, 12.952600819268481];
            fNearOrbs = 1 / 3600 ./ [85.1513423, 84.575556990340160723, ...
                84.783999521416234302, 85.098596922214568394, 84.471719596866705615, ...
                84.888606553513909603, 84.993472034115839620, 85.415537694012940, ...
                85.521709897525156, 84.368136863961226, 85.628146376422208164];
            
            f = [fSyn, fTA, fOrb];

            % Harmonics
            f = [f, 2*fSyn, ...
                    3*fSyn, ...
                    4*fSyn, ...
                    2*fTA, ...
                    2*fOrb, ...
                    fSyn - fTA, ... % 1st harmonic beats
                    fSyn + fTA, ...
                    fSyn - fOrb, ...
                    fSyn + fOrb, ...
                    2*fSyn - fTA, ... % 2nd harmonic beats
                    2*fSyn + fTA, ...
                    2*fTA - fOrb, ...
                    2*fOrb - fTA, ...
                    fSyn - 2*fOrb, ...
                    fSyn - 2*fTA, ...
                    fTA + fOrb, ...
                    fNearOrbs, ...
                    fNearBeats, ...
                    fPar - fJyr, ... % Solar oscillation periods due to 
                    fPar - 2*fJyr, ... % magnetopause current fields
                    fOrbAdj - fJyr, ...
                    fOrbAdj - 2*fJyr];

        case 'Ganymede'
            fEuropaTA = 3.281745587e-6;
            fOrbEuropa = 101.3747235 / 360 / 86400;
            fMystery = 1 / 3600 / 34.724522173543868;
            fMystery2 = 1 / 3600 / 150.271894222476305458;
            f = [fSyn, fOrb];

            f = [f, 2*fSyn, ...
                    3*fSyn, ...
                    4*fSyn, ...
                    5*fSyn, ...
                    6*fSyn, ...
                    fSyn - fOrb, ... % 1st harmonic beats
                    fSyn + fOrb, ...
                    2*fSyn - fOrb, ... % 2nd harmonic beats
                    2*fSyn + fOrb, ...
                    3*fSyn - fOrb, ... % 3rd harmonic beats
                    3*fSyn + fOrb, ...
                    fMystery, ...
                    fSyn - fMystery, ...
                    fSyn + fMystery, ...
                    fEuropaTA/2, ... % Half of Europa's true anomaly oscillation
                    fOrbAdj, ...
                    fPar - fOrbEuropa, ...
                    2*fSyn - 5*fOrb, ...
                    fMystery2, ...
                    fSyn - fMystery2, ...
                    1 / 3600 / 4.573237865242181, ...
                    1 / 3600 / 6.208585640926228, ...
                    1 / 3600 / 3.188814749737327, ...
                    1 / 3600 / 3.906250548182006, ...
                    2*fMystery, ...
                    fPar - fJyr, ... % Solar oscillation periods due to 
                    fPar - 2*fJyr, ... % magnetopause current fields
                    fOrbAdj - fJyr, ...
                    fOrbAdj - 2*fJyr];

        case 'Callisto'
            fSheet1 = 1 / 3600 / 15.120553206749488;
            fSheet2 = 1 / 3600 / 7.6696338880659605;
            fSheet3 = 1 / 3600 / 3.8072842207111743;
            fSheet4 = 1 / 3600 / 3.059002331397538;

            f = [fSyn, fOrbAdj];

            % Harmonics
            f = [f, 2*fSyn, ...
                    3*fSyn, ...
                    4*fSyn, ...
                    5*fSyn, ...
                    6*fSyn, ...
                    2*fOrb, ...
                    fSyn - fOrb, ... % 1st harmonic beats
                    fSyn + fOrb, ...
                    2*fSyn - fOrb, ... % 2nd harmonic beats
                    2*fSyn + fOrb, ...
                    fSheet1, ...
                    fSheet2, ...
                    fSheet3, ...
                    fSheet4, ...
                    fPar - fJyr, ... % Solar oscillation periods due to 
                    fPar - 2*fJyr, ... % magnetopause current fields
                    fOrbAdj - fJyr, ...
                    fOrbAdj - 2*fJyr];

        %% Saturn moons         
        case 'Mimas'
            fTA = 1 / 3600 / 22.67814677274641;
            fOrbTAbeat1 = 1 / 3600 / 22.55964638685534;
            fOrbTAbeat2 = 1 / 3600 / 22.50213602844169;
            f = [fOrb, fOrbAdj, fTA, fOrbTAbeat1, fOrbTAbeat2];

            % Harmonics
            f = [f, 2*fOrb, ...  
                    2*fOrbAdj, ...
                    2*fTA, ...  
                    2*fOrbTAbeat1, ...
                    3*fOrb, ...
                    3*fOrbAdj, ...
                    3*fTA, ...
                    fPar - fSyr, ... % Solar oscillation periods due to 
                    fPar - 2*fSyr, ... % magnetopause current fields
                    fOrbAdj - fSyr, ...
                    fOrbAdj - 2*fSyr];  

        case 'Enceladus'
            fTA = 1 / 3600 / 32.927200612354675; % True anomaly period
            f = [fOrb, fTA];

            f = [f, 2*fTA, ...
                    1 / 3600 / 32.917867508555119116, ...
                    1 / 3600 / 32.941210199582918960, ...
                    1 / 3600 / 32.838749203627905615, ...
                    1 / 3600 / 32.936539015933050223, ...
                    1 / 3600 / 32.913202935703473884, ...
                    1 / 3600 / 32.834107031435593171, ...
                    1 / 3600 / 32.866629845374262686, ...
                    fPar - fSyr, ... % Solar oscillation periods due to 
                    fPar - 2*fSyr, ... % magnetopause current fields
                    fOrbAdj - fSyr, ...
                    fOrbAdj - 2*fSyr];

        case 'Dione'
            fTA = 1 / 3600 / 65.872263600244693293;
            f = [fOrb, fTA];
            
            f = [f, ...
                    fPar - fSyr, ... % Solar oscillation periods due to 
                    fPar - 2*fSyr, ... % magnetopause current fields
                    fOrbAdj - fSyr, ...
                    fOrbAdj - 2*fSyr];

        case 'Rhea'
            f = fOrb;
            
            f = [f, ...
                    fPar - fSyr, ... % Solar oscillation periods due to 
                    fPar - 2*fSyr, ... % magnetopause current fields
                    fOrbAdj - fSyr, ...
                    fOrbAdj - 2*fSyr];

        case 'Titan'
            f = fOrb;
            
            f = [f, 2*fOrb, ...
                    fPar - fSyr, ... % Solar oscillation periods due to 
                    fPar - 2*fSyr, ... % magnetopause current fields
                    fOrbAdj - fSyr, ...
                    fOrbAdj - 2*fSyr];

        %% Uranus moons   
        case 'Miranda'
            f = [fSyn, fOrb];

            % Harmonics
            f = [f, 2*fSyn, ...
                    3*fSyn, ...
                    4*fSyn, ...
                    2*fOrb, ...
                    fOrb - fSyn, ... % 1st harmonic beats
                    fSyn + fOrb, ...
                    2*fSyn - fOrb, ... % 2nd harmonic beats
                    2*fSyn + fOrb, ...
                    2*fOrb + fSyn, ...
                    3*fSyn - fOrb, ... % 3rd harmonic beats
                    3*fSyn + fOrb, ...
                    2*fOrb + 2*fSyn]; % Double harmonic beats

        case 'Ariel'
            f = [fSyn, fOrb];

            % Harmonics
            f = [f, 2*fSyn, ...
                    3*fSyn, ...
                    fSyn - fOrb, ... % 1st harmonic beats % 40.09
                    fSyn + fOrb];

        case 'Umbriel'
            f = [fSyn, fOrb];

            % Harmonics
            f = [f, 2*fSyn, ...
                    3*fSyn, ...
                    4*fSyn, ...
                    fSyn - fOrb, ... % 1st harmonic beats
                    fSyn + fOrb];

        case 'Titania'
            f = [fSyn, fOrb];

            % Harmonics
            f = [f, 2*fSyn, ...
                    3*fSyn, ...
                    4*fSyn, ...
                    fSyn - fOrb, ... % 1st harmonic beats
                    fSyn + fOrb];

        case 'Oberon'
            f = [fSyn, fOrb];

            % Harmonics
            f = [f, 2*fSyn, ...
                    3*fSyn, ...
                    4*fSyn, ...
                    fSyn - fOrb, ... % 1st harmonic beats
                    fSyn + fOrb];

        %% Neptune moons
        case 'Triton'
            fSyn = fPar + fOrb; % Retrograde orbit
            f = [fSyn, fOrb];

            % Harmonics
            f = [f, 2*fSyn, ...
                    3*fSyn, ...
                    2*fOrb, ...
                    fSyn - fOrb, ... % 1st harmonic beats
                    fSyn + fOrb, ...
                    fSyn - 2*fOrb, ...
                    fSyn + 2*fOrb, ...
                    fSyn - 3*fOrb, ...
                    fSyn + 3*fOrb, ...
                    2*fSyn - fOrb, ... % 2nd harmonic beats
                    2*fSyn + fOrb, ...
                    2*fSyn - 2*fOrb, ...
                    2*fSyn + 2*fOrb];
                    
    end
    
    f = sort(f, 'descend');
end
